### PR TITLE
[Blocked] Support multiple types per attributes. Separated by a comma like `@param` in ruby docs would be

### PR DESCRIPTION
**Pull request by helgi**
My use case is that I accept both an array or a string where the cookbook will do the appropriate conversion to the internal format I desire. Not the most common thing but it's fairly common practice to be flexible with inputs if you can do it.

I realize this isn't really supported / intended in Chef as such but then again what uses the metadata, really? Maybe a LWRP couldn't pull this off but well... Looking for feedback if this is even sensible

### CODE REVIEW

**Comment by helgi** [comment]
I need to fix this up... Not sure why I pushed the PR :)

**Comment by helgi** [comment]
Okay all better, should at least be enough to talk about

**Comment by helgi** [comment]
I ran this with Chef and turns out Chef does fairly strict validation on the type even if it doesn't use it

```
>>>>>> Message: Failed to complete #converge action: [An error occurred while reading the Berksfile:

  Could not parse `/package/metadata.rb': uninitialized constant Ridley::Mixin::ParamsValidate::ValidationFailed]
```

Not the best error message but it is when I do `:type => 'array,string'` or similar. I'd quite like this feature still but I guess it's not possible unless I'd manage to patch Chef or surprise that error somehow...

**Comment by reset** [comment]
@helgi sorry for the late response, I haven't peeked at this project in a bit. I don't think we should merge this unless this is something that is described as officially supported in the [Chef metadata.rb](https://docs.chef.io/config_rb_metadata.html)

**Comment by helgi** [comment]
I agree. It anyway won't function without upstream changes since Chef bombs
out during its own validation step.

Can come back to this if I find the motivation to contribute that to chef
itself :)

**Pull request closed without merging**
